name: receitanamao
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_signin_button: ^2.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.1.2
  path: ^1.9.1
  http: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Image/

  fonts:
    - family: TTNeoris
      fonts:
        - asset: assets/fonts/TTNeorisTrialBold.ttf
        - asset: assets/fonts/TTNeorisTrialDemiBold.ttf
    - family: DoggiesSilhouette
      fonts:
        - asset: assets/fonts/DoggiesSilhouetteFont.ttf
    - family: OswaldBold
      fonts:
      - asset: assets/fonts/OswaldBold.ttf
    - family: OpenSanst
      fonts:
      - asset: assets/fonts/OpenSanst.ttf 
  
flutter_launcher_icons:
  android: true
  image_path: "assets/Image/left.png"


